Document: serval-crypto
Title: Debian serval-crypto Manual
Author: <insert document author here>
Abstract: This manual describes what serval-crypto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/serval-crypto/serval-crypto.sgml.gz

Format: postscript
Files: /usr/share/doc/serval-crypto/serval-crypto.ps.gz

Format: text
Files: /usr/share/doc/serval-crypto/serval-crypto.text.gz

Format: HTML
Index: /usr/share/doc/serval-crypto/html/index.html
Files: /usr/share/doc/serval-crypto/html/*.html
